[env]
TERM = "xterm-256color"
[window]
decorations = "none"
startup_mode = "Maximized"
padding = { x = 0, y = 0 }
[font]
size = 14

[font.normal]
family = "FiraCode Nerd Font"

[font.bold]
family = "FiraCode Nerd Font"

[font.italic]
family = "FiraCode Nerd Font"

[font.bold_italic]
family = "FiraCode Nerd Font"

[general]
import = ["~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml"]

# test
